# Generated by Django 4.2.2 on 2023-06-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_remove_congregation_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congregation',
            old_name='floor',
            new_name='place',
        ),
    ]
