# Generated by Django 4.2.2 on 2023-06-27 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0003_rename_floor_congregation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
