# Generated by Django 4.2.2 on 2023-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0004_congregation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={'ordering': ('time',)},
        ),
        migrations.AlterField(
            model_name='congregation',
            name='prayer',
            field=models.CharField(choices=[('FAJR', 'Fajr'), ('ZUHR', 'Zuhr'), ('ASR', 'Asr'), ('MAGHRIB', 'Maghrib'), ('ISHA', 'Isha')], max_length=10),
        ),
    ]
