# Generated by Django 4.2.2 on 2023-06-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_floor_office'),
        ('prayer', '0005_alter_congregation_options_alter_congregation_prayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregations', to='org.floor'),
        ),
    ]
