# Generated by Django 4.2.2 on 2023-06-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0006_alter_congregation_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congregation',
            old_name='place',
            new_name='floor',
        ),
    ]
