# Generated by Django 4.2.2 on 2023-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_floor_imam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='imam',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
